/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <time.h>
#include "rHORA.h"
int obten_segundos (time_t *s)
{
//Obtención de los segundos desde el sistema operativo
time(s);
if(s == NULL)
return -1;
else
return 0;
}
segactual *
obten_segundos_1_svc(void *argp, struct svc_req *rqstp)
{
	int resultado;
	time_t s;
	segactual *segundos_actuales;
	//se reserva espacio para almacenar el resultado
	segundos_actuales = (segactual *) malloc (sizeof(struct segactual));
	//Se llama al procedimiento local
	resultado = obten_segundos(&s);
	if(resultado == -1) //error de ejecución del procedimiento local
	segundos_actuales->status = HORA_NOK;
	else //el procedimiento local se ejecutó correctamente
	{
	segundos_actuales->status = HORA_OK;
	segundos_actuales->segactual_u.segundos = s;
	}
	return segundos_actuales;
}